import { Flag } from "./Flag";

export const flagsEasy: Flag[] = [
    { name: 'Czech Republic', image: 'assets/flags/cz.png' },
    { name: 'Slovakia', image: 'assets/flags/sk.png' },
    { name: 'Germany', image: 'assets/flags/de.png' },
    { name: 'France', image: 'assets/flags/fr.png' },
    { name: 'Italy', image: 'assets/flags/it.png' },
    { name: 'Spain', image: 'assets/flags/es.png' },
    { name: 'United States', image: 'assets/flags/us.png' },
    { name: 'Canada', image: 'assets/flags/ca.png' },
    { name: 'United Kingdom', image: 'assets/flags/gb.png' },
    { name: 'Australia', image: 'assets/flags/au.png' },
    { name: 'Russia', image: 'assets/flags/ru.png' },
    { name: 'Japan', image: 'assets/flags/jp.png' },
    { name: 'Brazil', image: 'assets/flags/br.png' },
    { name: 'Argentina', image: 'assets/flags/ar.png' },
    { name: 'China', image: 'assets/flags/cn.png' },
    { name: 'India', image: 'assets/flags/in.png' },
    { name: 'South Korea', image: 'assets/flags/kr.png' },
    { name: 'Egypt', image: 'assets/flags/eg.png' },
    { name: 'Greece', image: 'assets/flags/gr.png' },
    { name: 'Turkey', image: 'assets/flags/tr.png' },
    { name: 'Cuba', image: 'assets/flags/cu.png' },
    { name: 'Mexico', image: 'assets/flags/mx.png' },
    { name: 'Costa Rica', image: 'assets/flags/cr.png' },
    { name: 'Nigeria', image: 'assets/flags/ng.png' },
  ];
  
  export const flagsMedium: Flag[] = [
    { name: 'Sweden', image: 'assets/flags/se.png' },
    { name: 'Norway', image: 'assets/flags/no.png' },
    { name: 'Netherlands', image: 'assets/flags/nl.png' },
    { name: 'Ireland', image: 'assets/flags/ie.png' },
    { name: 'Switzerland', image: 'assets/flags/ch.png' },
    { name: 'Thailand', image: 'assets/flags/th.png' },
    { name: 'Denmark', image: 'assets/flags/dk.png' },
    { name: 'Finland', image: 'assets/flags/fi.png' },
    { name: 'Austria', image: 'assets/flags/at.png' },
    { name: 'Belgium', image: 'assets/flags/be.png' },
    { name: 'Portugal', image: 'assets/flags/pt.png' },
    { name: 'Poland', image: 'assets/flags/pl.png' },
    { name: 'Hungary', image: 'assets/flags/hu.png' },
    { name: 'Croatia', image: 'assets/flags/hr.png' },
    { name: 'Romania', image: 'assets/flags/ro.png' },
    { name: 'Bulgaria', image: 'assets/flags/bg.png' },
    { name: 'Greece', image: 'assets/flags/gr.png' },
    { name: 'Ukraine', image: 'assets/flags/ua.png' },
    { name: 'Estonia', image: 'assets/flags/ee.png' },
    { name: 'Latvia', image: 'assets/flags/lv.png' },
    { name: 'Lithuania', image: 'assets/flags/lt.png' },
    { name: 'Slovenia', image: 'assets/flags/si.png' },
    { name: 'Serbia', image: 'assets/flags/rs.png' },
    { name: 'Montenegro', image: 'assets/flags/me.png' },
  ];

  export const flagsHard: Flag[] = [
    { name: 'Vietnam', image: 'assets/flags/vn.png' },
    { name: 'Philippines', image: 'assets/flags/ph.png' },
    { name: 'Malaysia', image: 'assets/flags/my.png' },
    { name: 'Indonesia', image: 'assets/flags/id.png' },
    { name: 'Singapore', image: 'assets/flags/sg.png' },
    { name: 'Saudi Arabia', image: 'assets/flags/sa.png' },
    { name: 'Iran', image: 'assets/flags/ir.png' },
    { name: 'Iraq', image: 'assets/flags/iq.png' },
    { name: 'Syria', image: 'assets/flags/sy.png' },
    { name: 'Lebanon', image: 'assets/flags/lb.png' },
    { name: 'Israel', image: 'assets/flags/il.png' },
    { name: 'Jordan', image: 'assets/flags/jo.png' },
    { name: 'Kuwait', image: 'assets/flags/kw.png' },
    { name: 'Oman', image: 'assets/flags/om.png' },
    { name: 'Yemen', image: 'assets/flags/ye.png' },
    { name: 'Qatar', image: 'assets/flags/qa.png' },
    { name: 'Bahrain', image: 'assets/flags/bh.png' },
    { name: 'United Arab Emirates', image: 'assets/flags/ae.png' },
    { name: 'Pakistan', image: 'assets/flags/pk.png' },
    { name: 'Afghanistan', image: 'assets/flags/af.png' },
    { name: 'Turkmenistan', image: 'assets/flags/tm.png' },
    { name: 'Kazakhstan', image: 'assets/flags/kz.png' },
    { name: 'Uzbekistan', image: 'assets/flags/uz.png' },
    { name: 'Tajikistan', image: 'assets/flags/tj.png' },
    { name: 'Kyrgyzstan', image: 'assets/flags/kg.png' },
  ];

  export const flagsExpert: Flag[] = [
    { name: 'Nepal', image: 'assets/flags/np.png' },
    { name: 'Bhutan', image: 'assets/flags/bt.png' },
    { name: 'Sri Lanka', image: 'assets/flags/lk.png' },
    { name: 'Bangladesh', image: 'assets/flags/bd.png' },
    { name: 'Myanmar', image: 'assets/flags/mm.png' },
    { name: 'Laos', image: 'assets/flags/la.png' },
    { name: 'Cambodia', image: 'assets/flags/kh.png' },
    { name: 'Mongolia', image: 'assets/flags/mn.png' },
    { name: 'Indonesia', image: 'assets/flags/id.png' },
    { name: 'Maldives', image: 'assets/flags/mv.png' },
    { name: 'Philippines', image: 'assets/flags/ph.png' },
    { name: 'Singapore', image: 'assets/flags/sg.png' },
    { name: 'Malaysia', image: 'assets/flags/my.png' },
    { name: 'Brunei', image: 'assets/flags/bn.png' },
    { name: 'Timor-Leste', image: 'assets/flags/tl.png' },
    { name: 'Mauritius', image: 'assets/flags/mu.png' },
    { name: 'Seychelles', image: 'assets/flags/sc.png' },
    { name: 'Fiji', image: 'assets/flags/fj.png' },
    { name: 'Solomon Islands', image: 'assets/flags/sb.png' },
    { name: 'Vanuatu', image: 'assets/flags/vu.png' },
    { name: 'Papua New Guinea', image: 'assets/flags/pg.png' },
    { name: 'Tuvalu', image: 'assets/flags/tv.png' },
    { name: 'Kiribati', image: 'assets/flags/ki.png' },
    { name: 'Marshall Islands', image: 'assets/flags/mh.png' },
    { name: 'Micronesia', image: 'assets/flags/fm.png' },
  ];

  export const flagsExtreme: Flag[] = [
    { name: 'Greenland', image: 'assets/flags/gl.png' },
    { name: 'Iceland', image: 'assets/flags/is.png' },
    { name: 'Faroe Islands', image: 'assets/flags/fo.png' },
    { name: 'New Zealand', image: 'assets/flags/nz.png' },
    { name: 'Samoa', image: 'assets/flags/ws.png' },
    { name: 'Tonga', image: 'assets/flags/to.png' },
    { name: 'Niue', image: 'assets/flags/nu.png' },
    { name: 'Cook Islands', image: 'assets/flags/ck.png' },
    { name: 'Falkland Islands', image: 'assets/flags/fk.png' },
    { name: 'Bermuda', image: 'assets/flags/bm.png' },
    { name: 'Bahamas', image: 'assets/flags/bs.png' },
    { name: 'Cayman Islands', image: 'assets/flags/ky.png' },
    { name: 'British Virgin Islands', image: 'assets/flags/vg.png' },
    { name: 'Turks and Caicos Islands', image: 'assets/flags/tc.png' },
    { name: 'Montserrat', image: 'assets/flags/ms.png' },
    { name: 'Anguilla', image: 'assets/flags/ai.png' },
    { name: 'Antarctica', image: 'assets/flags/aq.png' },
    { name: 'Northern Mariana Islands', image: 'assets/flags/mp.png' },
    { name: 'Guam', image: 'assets/flags/gu.png' },
    { name: 'American Samoa', image: 'assets/flags/as.png' },
    { name: 'Palau', image: 'assets/flags/pw.png' },
    { name: 'Federated States of Micronesia', image: 'assets/flags/fm.png' },
    { name: 'Marshall Islands', image: 'assets/flags/mh.png' },
    { name: 'Nauru', image: 'assets/flags/nr.png' },
    { name: 'Tuvalu', image: 'assets/flags/tv.png' },
  ];
  
  
  
  